import pygame as pg

# define some constants
DIRECTION_FRONT = 'front'
DIRECTION_BACK = 'back'
DIRECTION_LEFT = 'left'
DIRECTION_RIGHT = 'right'

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

WIDTH = 1024
HEIGHT = 768
FPS = 64
TITLE = 'Tomb of Rasputin'
BACKGROUND_COLOR = DARKGREY

TILE_SIZE = 64
GRID_WIDTH = WIDTH / TILE_SIZE
GRID_HEIGHT = HEIGHT / TILE_SIZE

PLAYER_HIT_RECT = pg.Rect(0, 0, TILE_SIZE, TILE_SIZE)
MOVE_SPEED = .2

PLAYER_BASE_PATH = 'player'
ZOMBIE_BASE_PATH = 'zombie'
